### ISSUE TITLE
Transition functions are not filtering out event data

### ISSUE THREAD

**Issue by mjstahl** [mjstahl/use-state-machine#8]
```html
<button data-testid='solid'
  disabled={!transition.toSolid}
  onClick={transition.freeze}>
  To Solid
</button>
```

When the above button is clicked, `freeze` will get called with a ClickEvent object, and the value will be set to the Event object. 

Not sure what the right course of action is here:
1. The functions on the transition object could ignore any value where `typeof arg === Event`. 
2. It could stay as is, and `console.warn` something like - An Event object was passed, you probably wanted data off that event object didn't care about setting the value -- Use `{() => transition.fn()}` instead of `{transition.fn}`.

Option 1 is nicer because we don't have to thunk event handlers. But that means we can't pass event objects (probably shouldn't anyway), and it means that there may be other edge cases and further handling of those cases complicates that code.

Option 2 Is probably better because it provides the most amount of flexibility (even for arguably wrong behavior) along with a warning to the User.

**Comment by BigAB** [comment]
Option 2 seems like the better choice to me
